/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ObjectDetection;

public class Library {
    public boolean someLibraryMethod() {
    	System.out.println("true");
        return true;
    }
}
